boatd:
    port: 2222
    interface: 0.0.0.0

plugin_directory: null

plugins:
    - opencpn:
        enabled: true
        destination_ip: 192.168.40.255
    - logger:
        enabled: false
        period: 1
        filename: /var/log/boatd/xpb
    - gpx_logger:
        enabled: true
        period: 1
        filename: /var/log/boatd/xpb-gpx

waypoint_file: '/home/pi/xpb/waypoints'

driver:
    file: /home/pi/xpb/xpb-boatd-driver/xpb_boatd_driver.py

behaviours:
    - waypoint:
        file: looped-waypoint-behaviour
    - station-keeping:
        file: station-keeping-behaviour
    - idle:
        file: idle-behaviour

wind_filtering:
    enabled: true
    rate_of_change: 75
